services:
  traefik:
    build:
      context: traefik
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file: .env
  redis:
    image: bitnami/redis:7.0.8
    env_file: .env
    volumes:
      - redis:/bitnami/redis/data
  redis-init:
    env_file: .env
    build:
      context: redis-init
      dockerfile: Dockerfile
  flask:
    env_file: .env
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - redis
      - redis-init
  nodejs:
    env_file: .env
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
  go:
    env_file: .env
    build:
      context: go
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    depends_on:
      - redis
      - redis-init
  fastapi:
    env_file: .env
    build:
      context: fastapi
      dockerfile: Dockerfile
    ports:
      - '3004:3000'
  goproxy:
    env_file: .env
    build:
      context: goproxy
      dockerfile: Dockerfile
    ports:
      - '3005:3000'
  nodejsproxy:
    env_file: .env
    build:
      context: nodejsproxy
      dockerfile: Dockerfile
    ports:
      - '3006:3000'
  quart:
    env_file: .env
    build:
      context: quart
      dockerfile: Dockerfile
    ports:
      - '3007:3000'
    depends_on:
      - redis
      - redis-init
  sanic:
    env_file: .env
    build:
      context: sanic
      dockerfile: Dockerfile
    ports:
      - '3008:3000'
    depends_on:
      - redis
      - redis-init
volumes:
  redis:
