[package]
name = "rust-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
bb8-redis = "0.13.1"
redis = "0.23.0"
serde = { version = "1.0.164", features = ["derive"]}
